import React, { useState, useEffect, useRef } from 'react';
import {
  Sparkles, Loader2, X, CheckCircle2, ListFilter,
  Target, FileText, Copy, Check, BrainCircuit,
  Clock, ChevronDown, ChevronUp, History, Wand2
} from 'lucide-react';

const SAMPLE_TRANSCRIPT = `[10:00 AM] Alice: Hey everyone, let's discuss our progress on CollabCode for the sprint review.
[10:01 AM] Bob: Sure! I completed the real-time code editor integration using Yjs and WebSockets. Multiple users can now type simultaneously without conflicts.
[10:02 AM] Charlie: Awesome. I finalized the WebRTC video calling feature. It now supports up to 5 participants with audio and video toggles.
[10:03 AM] Alice: That's great progress. One issue we noticed was managing meeting outcomes. Let's decide on adding an AI Meeting Summary feature.
[10:04 AM] Bob: Agreed. We can use the Google Gemini API to analyze the meeting transcript and extract key discussion points, decisions, and action items.
[10:05 AM] Charlie: Sounds solid. Let's make sure the summary is also stored in MongoDB for future reference.
[10:06 AM] Alice: Perfect, let's finalize that decision. Bob, please implement the Gemini backend endpoint and MongoDB schema by Thursday. Charlie, integrate the summary modal in the frontend. I will handle testing and prepare the final presentation.`;

const SectionCard = ({ icon, label, color, borderColor, items, renderItem }) => {
  if (!items || items.length === 0) return null;
  return (
    <div className={`bg-[#1a1a1a] border ${borderColor} rounded-xl p-4 shadow-sm`}>
      <div className={`flex items-center gap-2 mb-3 ${color} font-semibold text-sm`}>
        {icon}
        <h4>{label}</h4>
        <span className={`ml-auto text-xs font-mono bg-black/30 px-2 py-0.5 rounded-full`}>
          {items.length}
        </span>
      </div>
      <ul className="space-y-2">
        {items.map((item, idx) => (
          <li key={idx} className="text-sm text-gray-300 flex items-start gap-2">
            {renderItem(idx)}
            <span className="leading-relaxed">{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
};

const MeetingSummary = ({ isOpen, onClose, onLeave, initialTranscript = '', autoGenerate = false }) => {
  const [transcript, setTranscript] = useState(initialTranscript || '');
  const [loading, setLoading] = useState(false);
  const [summaryData, setSummaryData] = useState(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [tab, setTab] = useState('generate');
  const [history, setHistory] = useState([]);
  const [loadingHistory, setLoadingHistory] = useState(false);
  const [showTranscriptPreview, setShowTranscriptPreview] = useState(false);
  const autoGeneratedRef = useRef(false);

  // When modal opens with a transcript and autoGenerate flag, auto-trigger summary
  useEffect(() => {
    if (isOpen && autoGenerate && initialTranscript && initialTranscript.trim().length > 0 && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      setTranscript(initialTranscript);
      // Small delay so the modal renders first
      setTimeout(() => {
        handleGenerate(initialTranscript);
      }, 400);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, autoGenerate]);

  // Reset state when modal is closed
  useEffect(() => {
    if (!isOpen) {
      autoGeneratedRef.current = false;
      setSummaryData(null);
      setError('');
    }
  }, [isOpen]);

  // Sync initialTranscript prop
  useEffect(() => {
    if (initialTranscript) {
      setTranscript(initialTranscript);
    }
  }, [initialTranscript]);

  if (!isOpen) return null;

  const handleGenerate = async (overrideTranscript) => {
    const textToUse = (overrideTranscript || transcript || '').trim();
    if (!textToUse) {
      setError('Please provide a meeting transcript to summarize.');
      return;
    }

    setLoading(true);
    setError('');
    setSummaryData(null);
    const token = localStorage.getItem('token');

    try {
      const response = await fetch('http://localhost:5000/api/meeting/summary', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ transcript: textToUse }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate summary.');
      }

      setSummaryData(data);
    } catch (err) {
      setError(err.message || 'An error occurred while generating summary.');
    } finally {
      setLoading(false);
    }
  };

  const fetchHistory = async () => {
    setTab('history');
    setLoadingHistory(true);
    setError('');
    const token = localStorage.getItem('token');

    try {
      const res = await fetch('http://localhost:5000/api/meeting/history', {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to fetch history');
      setHistory(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoadingHistory(false);
    }
  };

  const handleCopy = () => {
    if (!summaryData) return;
    const textToCopy = `MEETING SUMMARY:\n${summaryData.summary}\n\nKEY DISCUSSION POINTS:\n${(summaryData.keyPoints || []).map(p => `• ${p}`).join('\n')}\n\nDECISIONS TAKEN:\n${(summaryData.decisions || []).map(d => `• ${d}`).join('\n')}\n\nACTION ITEMS:\n${(summaryData.actionItems || []).map(a => `• ${a}`).join('\n')}`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const transcriptLines = transcript ? transcript.split('\n').filter(Boolean).length : 0;
  const transcriptWords = transcript ? transcript.split(/\s+/).filter(Boolean).length : 0;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-sm p-4">
      <div className="bg-[#161616] border border-gray-800 rounded-2xl w-full max-w-3xl max-h-[92vh] flex flex-col shadow-2xl overflow-hidden text-gray-200">

        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-800 flex justify-between items-center bg-[#1a1a1a] shrink-0">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-gradient-to-br from-blue-600/20 to-violet-600/20 text-blue-400 border border-blue-500/20 shadow-sm">
              <BrainCircuit size={20} />
            </div>
            <div>
              <h2 className="text-base font-bold text-white tracking-tight">AI Meeting Summary</h2>
              <p className="text-[11px] text-gray-400">Powered by Google Gemini · Auto-generated from call transcript</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {/* Navigation Tabs */}
            <div className="flex bg-gray-900 p-1 rounded-lg border border-gray-800">
              <button
                onClick={() => setTab('generate')}
                className={`px-3 py-1.5 text-xs font-semibold rounded-md transition-all flex items-center gap-1.5 ${
                  tab === 'generate' ? 'bg-blue-600 text-white shadow-sm' : 'text-gray-400 hover:text-white'
                }`}
              >
                <Wand2 size={12} />
                Generate
              </button>
              <button
                onClick={fetchHistory}
                className={`px-3 py-1.5 text-xs font-semibold rounded-md transition-all flex items-center gap-1.5 ${
                  tab === 'history' ? 'bg-blue-600 text-white shadow-sm' : 'text-gray-400 hover:text-white'
                }`}
              >
                <History size={12} />
                History
              </button>
            </div>

            <button
              onClick={onClose}
              className="text-gray-400 hover:text-white p-1.5 rounded-lg hover:bg-gray-800 transition-colors"
              title="Close"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Auto-generate notice banner */}
        {autoGenerate && !error && (
          <div className="px-6 py-2.5 bg-gradient-to-r from-blue-600/10 to-violet-600/10 border-b border-blue-500/20 flex items-center gap-2 shrink-0">
            <Sparkles size={13} className="text-blue-400 shrink-0" />
            <p className="text-xs text-blue-300">
              Your call has ended. We captured your conversation and are generating an AI summary automatically.
            </p>
          </div>
        )}

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto custom-scrollbar flex-1 flex flex-col gap-5">
          {tab === 'history' ? (
            /* ── History Tab ── */
            <div className="flex flex-col gap-4">
              <h3 className="text-xs font-semibold uppercase tracking-wider text-gray-400 flex items-center gap-2">
                <History size={13} />
                Saved Meeting Summaries
              </h3>
              {loadingHistory ? (
                <div className="flex items-center justify-center py-12 text-gray-500 text-sm gap-2">
                  <Loader2 size={18} className="animate-spin" />
                  Loading meeting history...
                </div>
              ) : history.length === 0 ? (
                <div className="text-center py-12 text-gray-500 text-sm">
                  <History size={32} className="mx-auto mb-3 opacity-30" />
                  No saved meeting summaries found.
                </div>
              ) : (
                <div className="flex flex-col gap-3">
                  {history.map((item, index) => (
                    <div key={item._id || index} className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-4 space-y-2 hover:border-gray-700 transition-colors">
                      <div className="flex justify-between items-center border-b border-gray-800 pb-2">
                        <span className="text-xs font-bold text-blue-400 font-mono flex items-center gap-1.5">
                          <BrainCircuit size={12} />
                          Meeting #{history.length - index}
                        </span>
                        <span className="text-[10px] text-gray-500 flex items-center gap-1">
                          <Clock size={10} />
                          {new Date(item.createdAt).toLocaleString()}
                        </span>
                      </div>
                      <p className="text-sm text-gray-200 font-medium leading-relaxed">{item.summary}</p>
                      {item.keyPoints?.length > 0 && (
                        <div className="text-xs text-gray-400 pt-1">
                          <span className="font-semibold text-gray-300">Key Points: </span>
                          {item.keyPoints.join(' · ')}
                        </div>
                      )}
                      {item.actionItems?.length > 0 && (
                        <div className="text-xs text-amber-400/70">
                          <span className="font-semibold">Actions: </span>
                          {item.actionItems.slice(0, 2).join(' · ')}
                          {item.actionItems.length > 2 && ` +${item.actionItems.length - 2} more`}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          ) : (
            /* ── Generate Tab ── */
            <>
              {/* Transcript Section */}
              <div className="flex flex-col gap-2">
                <div className="flex justify-between items-center">
                  <label className="text-xs font-semibold uppercase tracking-wider text-gray-400 flex items-center gap-1.5">
                    <FileText size={13} className="text-blue-400" />
                    Meeting Transcript
                    {transcriptLines > 0 && (
                      <span className="ml-2 text-[10px] font-mono text-gray-500 normal-case tracking-normal">
                        {transcriptLines} lines · {transcriptWords} words
                      </span>
                    )}
                  </label>
                  <div className="flex items-center gap-2">
                    {transcript && (
                      <button
                        type="button"
                        onClick={() => setShowTranscriptPreview(v => !v)}
                        className="text-xs text-gray-400 hover:text-gray-200 transition-colors flex items-center gap-1"
                      >
                        {showTranscriptPreview ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
                        {showTranscriptPreview ? 'Collapse' : 'Preview'}
                      </button>
                    )}
                    {!transcript && (
                      <button
                        type="button"
                        onClick={() => setTranscript(SAMPLE_TRANSCRIPT)}
                        className="text-xs text-blue-400 hover:text-blue-300 transition-colors font-medium underline underline-offset-2"
                      >
                        Load Demo
                      </button>
                    )}
                  </div>
                </div>

                {/* If transcript from call, show collapsible preview; else editable textarea */}
                {transcript && autoGenerate ? (
                  showTranscriptPreview && (
                    <div className="bg-[#0d0d0d] border border-gray-800 rounded-xl p-3.5 max-h-36 overflow-y-auto custom-scrollbar">
                      <pre className="text-[11px] font-mono text-gray-400 whitespace-pre-wrap break-words leading-relaxed">
                        {transcript}
                      </pre>
                    </div>
                  )
                ) : (
                  <textarea
                    rows={4}
                    value={transcript}
                    onChange={(e) => setTranscript(e.target.value)}
                    placeholder="Paste or review the meeting conversation transcript here..."
                    className="w-full bg-[#1e1e1e] border border-gray-800 rounded-xl p-3.5 text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:border-blue-500/60 focus:ring-1 focus:ring-blue-500/40 font-mono transition-all resize-y"
                  />
                )}
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-3">
                <button
                  onClick={() => handleGenerate()}
                  disabled={loading || !transcript.trim()}
                  className="flex-1 bg-gradient-to-r from-blue-600 to-violet-600 hover:from-blue-500 hover:to-violet-500 disabled:from-gray-800 disabled:to-gray-800 disabled:text-gray-500 text-white font-semibold py-2.5 px-4 rounded-xl flex items-center justify-center gap-2 transition-all shadow-lg hover:shadow-blue-600/25 disabled:shadow-none"
                >
                  {loading ? (
                    <>
                      <Loader2 size={18} className="animate-spin" />
                      <span>Analyzing with Gemini AI...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles size={18} />
                      <span>{summaryData ? 'Regenerate Summary' : 'Generate Summary'}</span>
                    </>
                  )}
                </button>
                {transcript && !autoGenerate && (
                  <button
                    type="button"
                    onClick={() => { setTranscript(''); setSummaryData(null); setError(''); }}
                    className="px-4 py-2.5 bg-gray-800 hover:bg-gray-700 text-gray-300 rounded-xl text-sm font-medium transition-colors"
                  >
                    Clear
                  </button>
                )}
              </div>

              {/* Error Message */}
              {error && (
                <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl text-red-400 text-sm flex items-start gap-2">
                  <X size={16} className="shrink-0 mt-0.5" />
                  <div>
                    <span className="font-semibold">Error: </span>
                    {error}
                  </div>
                </div>
              )}

              {/* Loading skeleton */}
              {loading && (
                <div className="flex flex-col gap-3 border-t border-gray-800/80 pt-5 animate-pulse">
                  <div className="h-4 bg-gray-800 rounded w-1/3"></div>
                  <div className="h-20 bg-gray-800 rounded-xl"></div>
                  <div className="h-24 bg-gray-800 rounded-xl"></div>
                  <div className="h-20 bg-gray-800 rounded-xl"></div>
                </div>
              )}

              {/* Structured AI Output */}
              {summaryData && !loading && (
                <div className="flex flex-col gap-4 border-t border-gray-800/80 pt-5">
                  <div className="flex justify-between items-center">
                    <h3 className="text-sm font-bold text-white tracking-tight flex items-center gap-2">
                      <BrainCircuit size={15} className="text-blue-400" />
                      Meeting Outcome
                    </h3>
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-white bg-gray-800 hover:bg-gray-700 px-3 py-1.5 rounded-lg transition-colors"
                    >
                      {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
                      {copied ? 'Copied!' : 'Copy All'}
                    </button>
                  </div>

                  {/* Summary */}
                  <div className="bg-[#1a1a1a] border border-blue-500/20 rounded-xl p-4 shadow-sm">
                    <div className="flex items-center gap-2 mb-2.5 text-blue-400 font-semibold text-sm">
                      <FileText size={16} />
                      <h4>Summary</h4>
                    </div>
                    <p className="text-sm text-gray-300 leading-relaxed">{summaryData.summary}</p>
                  </div>

                  <SectionCard
                    icon={<ListFilter size={16} />}
                    label="Key Discussion Points"
                    color="text-purple-400"
                    borderColor="border-purple-500/20"
                    items={summaryData.keyPoints}
                    renderItem={() => <span className="text-purple-400 mt-1 shrink-0">•</span>}
                  />

                  <SectionCard
                    icon={<CheckCircle2 size={16} />}
                    label="Decisions Taken"
                    color="text-emerald-400"
                    borderColor="border-emerald-500/20"
                    items={summaryData.decisions}
                    renderItem={() => <span className="text-emerald-400 mt-0.5 shrink-0">✓</span>}
                  />

                  <SectionCard
                    icon={<Target size={16} />}
                    label="Action Items"
                    color="text-amber-400"
                    borderColor="border-amber-500/20"
                    items={summaryData.actionItems}
                    renderItem={(idx) => (
                      <span className="text-amber-400 font-mono text-xs mt-0.5 shrink-0">[{idx + 1}]</span>
                    )}
                  />
                </div>
              )}
            </>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-gray-800 bg-[#1a1a1a] flex justify-between items-center shrink-0">
          <p className="text-[10px] text-gray-600">
            Summaries are saved to MongoDB for your history.
          </p>
          <button
            onClick={autoGenerate ? (onLeave || onClose) : onClose}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              autoGenerate
                ? 'bg-blue-600 hover:bg-blue-500 text-white shadow-sm'
                : 'bg-gray-800 hover:bg-gray-700 text-gray-300'
            }`}
          >
            {autoGenerate ? 'Done & Leave Room' : 'Close'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default MeetingSummary;
